server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

spring:
  application:
    name: retroboy
  mvc:
    servlet:
      path: /api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/retroboy
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stickies
  ai:
    mcp:
      server:
        name: mcp-retroboy
        instructions: This server provides tools to itegrate Stickies retro data

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

x402:
  facilitator:
    base-url: https://facilitator.mogami.tech
  default-network: base-sepolia
  default-payto: "0xBCe85b3943DB033e90ed0b20Df9503Cf33101B8D"
  client:
    fromaddress: "0xdE71133862c99586618231E02c0eaCF45440C3c4"
    fromprivatekey: ${X402_CLIENT_PRIVATE_KEY}

logging:
  level:
    root: INFO
    org.springframework.boot: INFO
    org.springframework.context: INFO
    org.springframework.web: INFO
    org.springframework.data: INFO
    org.apache.tomcat: INFO
