server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

spring:
  application:
    name: retroboy
  mvc:
    servlet:
      path: /api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/retroboy
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stickies
  ai:
    mcp:
      server:
        name: mcp-retroboy
        instructions: This server provides tools to itegrate Stickies retro data
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.apache.tomcat: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    org.springframework.data.mongodb: INFO
